apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: cleanup
      image: alpine
      command:
        - /bin/sh
        - -c
      args:
        - |
          echo "Cleaning up workspace..."
          rm -rf /workspace/*

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose-test
spec:
  workspaces:
    - name: source
  steps:
    - name: install-deps
      image: python:3.11
      script: |
        pip install -r /workspace/source/requirements.txt
        pip install nose
    - name: run-tests
      image: python:3.11
      script: |
        cd /workspace/source
        nosetests